apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api-2
  template:
    metadata:
      labels:
        app: my-api-2
    spec:
      containers:
      - name: my-api-container
        image: ltonrosendo/docker-fastapi-app:latest
        ports:
        - containerPort: 80
