name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/docker-fastapi-app:latest
            ${{ secrets.DOCKERHUB_USER }}/docker-fastapi-app:${{ github.run_number }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: Eliton-jpg/Gitops
          path: gitops-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag in values.yaml
        run: |
          sed -i 's|repository:.*|repository: '${{ secrets.DOCKERHUB_USER }}/docker-fastapi-app:${{ github.run_number }}'|' gitops-repo/my-api/values.yaml

      - name: Commit and push changes
        run: |
          cd gitops-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add my-api/values.yaml
          git commit -m "Update image tag to ${{ secrets.DOCKERHUB_USER }}/docker-fastapi-app:${{ github.run_number }}"
          git push origin main
